### ISSUE TITLE
I didn't see the need of passing return_middle as function parameters.

### ISSUE THREAD

**Issue by LingboTang** [gheja/trilateration.js#1]
Here is your definition: `function trilaterate(p1, p2, p3, return_middle)`

`* parameter (return_middle) is set to true when the middle of the two solution`

Logically speaking, you can't not determine this bool before calculating and comparing the radius.

Also, in your use example in `example.html`:

`p4 = trilaterate(p1, p2, p3);`

Your are not passing `return_middle` in it.

**Comment by gheja** [comment]
You're right, I left out the fourth parameter in the example.
It supposed to be an optional parameter that when not defined (by not passing anything the value is `undefined` which evaluates to `false` when using as a boolean) have the same effect as when defined as `false`. As far as I know the ES6 has a way to give default values to parameters to use when they're omitted but I am not sure if that's widely supported or not, so I left it the way I usually see.

**Comment by LingboTang** [comment]
Nevermind, it's a easy fix in other people's implementation, but just a question to clear the logic. Your algorithm is fine though. I'll close it for now.
