### ISSUE TITLE
Calculation fails due to floating point math flaw

### ISSUE THREAD

**Issue by gheja** [gheja/trilateration.js#2]
The calculation fails when `Math.sqrt()` should receive zero as parameter but the value is less than zero due to floating point math.

```
var p1 = {x:69, y:0,  r:69, z:0}
var p2 = {x:0,  y:50, r:50, z:0};
var p3 = {x:0,  y:80, r:80, z:0};

[...]

z = Math.sqrt(sqr(p1.r) - sqr(x) - sqr(y));:

sqr(p1.r): 4761
-sqr(x) - sqr(y): -4761.000000000017
sqr(p1.r) - sqr(x) - sqr(y): -0.000000000017
z: Math.sqrt(-0.000000000017)
therefore: z: NaN
```

See:
http://stackoverflow.com/questions/34056344/3d-trilateration-in-javascript
http://stackoverflow.com/questions/588004/is-floating-point-math-broken

**Comment by century2210** [comment]
Good morning - I am looking for a good forum to post questions regarding trilateration in python. I am an OSINT student who is learning to apply scripts to perform more advanced analyses. I am have trouble getting the script to work as it is returning large numbers that don't translate to coordinates. Can you tell a forum to get some info?
