### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by gheja** [gheja/trilateration.js#3]

**Comment by roblabs** [comment]
A couple of other ideas for unit tests

* Create Node package wrapper for trilateration.js
* Sample notebook from [RunKit.com](http://runkit.com)
* Here is RunKit Notebook with sample data

https://github.com/gheja/trilateration.js/blob/master/trilateration.js

```
points (0,0) (0,100) and (100, 0) and distances 107.70, 40.0 and 116.619 

returns ~(40,100)
```


```
trilaterate(  {x: 0, y:0, z:0, r:107.70}, {x: 100, y:0, z:0, r:40.0}, {x: 0, y:100, z:0, r:116.619}, true);
```

**Comment by gheja** [comment]
Thanks for the tip, although I am more familiar with the Travis-CI - node.js - Mocha combo. I have created the tests for this but will definetly look into this RunKit, seems exciting.
