### ISSUE TITLE
sqrt 

### ISSUE THREAD

**Issue by kenchen12** [gheja/trilateration.js#7]
read wrong, sorry.

**Comment by kenchen12** [comment]
misread the function name.

**Comment by gheja** [comment]
I have not defined a `sqrt()` function, I am using the built in `Math.sqrt()`. The `sqr()` which returns `x^2` as it should, I believe.

**Comment by gheja** [comment]
Oh, you just closed it :D No problem.

**Comment by axelrodriguez2017** [comment]
Hello everybody I don't know how your figure out this
formula anyone can help me? According to this paper



-----Original message-----

**Comment by gheja** [comment]
Hello @axelrodriguez2017, check out https://en.wikipedia.org/wiki/Trilateration , there's description for the formula and how it works.

**Comment by axelrodriguez2017** [comment]
Thank you I red this information 100 times but according to this paper told me 

 it's easy

      The result is x = 6.11
                          y =8.530


                    and Ax= b 


and it's easy to resolve for matrices
     Ap1(0.0)
     Ap2(30.0)
     Ap3(15,30)


     A=( 30-0.  0-0.  0-0
            15-0 30-0 0-0) 


and x =( x -0
              y-0
               z-0)
   
     b=( d1 11.81
            d2 24.55
            d3 3.25)

      Ax= b

       ( 30 -900
         45-450) =. b
and I used Gauss Jordan
   Matrices 3 X 2 and didn't get the result it's make me crazy and the author say it's easy to resolve may you help me



-----Original message-----
